name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-deps
        name: Install dependencies
        run: bun install

      - id: test
        name: Run test
        run: bun test

      - name: Build (if necessary)
        run: bun run build

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          bun publish

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0