name: Update Version in README

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF##*/}"

      - name: Update README.md version
        run: |
          version=${{ steps.get_version.outputs.VERSION }}
          sed -i "s/version-[0-9.]\+/version-${version}/g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update README.md to version ${{ steps.get_version.outputs.VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
